### ISSUE TITLE
You should write display: flex by final spec instead of display: box

### ISSUE THREAD

**Issue by michaelevensen** [juliancwirko/meteor-s-jeet#5]
I'm getting this error: 

`You should write display: flex by final spec instead of display: box`

and it's related to me using `display: flex`. It's coming from autoprefixer, and after reading a bit I found this: 

```
PostCSS 4.1 brings new APIs for plugins. Most important new API for Autoprefixer is a warnings.

Outdated articles and copy-paste developing created many pain for us. There are many code examples with display: box value by 2009 spec, instead of display: flex in final spec.
```

Am I getting this error because Autoprefixer isn't updated to the newest version? If so, would love to get it updated for this package.

**Comment by juliancwirko** [comment]
Main package `autoprefixer-stylus` is up to date, and all dependencies should be also up to date. I think the problem is `nib`, it could autogenerate `display: box` for you then Autoprefixer is fired after it and it sees the problem with display: box. But `nib` is also up to date. It could be old syntax in it. You can try to run your app without including nib. I think they will fix this soon in nib.

**Comment by KovalevEvgeniy** [comment]
u should set `flex-version = flex`
